### ISSUE TITLE
ModuleNotFoundError: No module named 'alarm'

### ISSUE THREAD

**Issue by thebmo** [C4ptainCrunch/ics.py#118]
I just `pip3 install ics`'ed and am on ics (0.3.1). I cant for the life of me get alarms working. I suspect something is wrong with the __init__.py file

```
>>> from ics import Alarm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Alarm'
```

```
>>> from ics import alarm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'alarm'
```

```
>>> e = Event(alarms=["foo", "bar"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() got an unexpected keyword argument 'alarms'
```

**Comment by thebmo** [comment]
ok is see that tag 0.3.1 was released after the alarm merge so I guess this is irellevent now. you may consider making a new release?

Guess I have a lot of refactoring to do as we used this implementation previously.
