### ISSUE TITLE
UnicodeDecodeError when loading a calendar

### ISSUE THREAD

**Issue by neilr8133** [C4ptainCrunch/ics.py#126]
ICS version: 0.3.1 (installed via Pip into a virtualenv)
Stack trace (sanitized):

    Traceback (most recent call last):
      File "ical.py", line 19, in <module>
        main(sys.argv[1])
      File "ical.py", line 8, in main
        c = Calendar(infile.read())
      File "xxxxxxxx/venv/lib/python2.7/site-packages/ics/icalendar.py", line 60, in __init__
        container = string_to_container(imports)
      File "xxxxxxxx/venv/lib/python2.7/site-packages/ics/parse.py", line 166, in string_to_container
        return lines_to_container(txt.split('\n'))
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2179: ordinal not in range(128)

Additional information via PDB:

    > xxxxxxxx/ical.py(1)<module>()
    -> from __future__ import print_function
    (Pdb) c
    Traceback (most recent call last):
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pdb.py", line 1314, in main
        pdb._runscript(mainpyfile)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pdb.py", line 1233, in _runscript
        self.run(statement)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/bdb.py", line 400, in run
        exec cmd in globals, locals
      File "<string>", line 1, in <module>
      File "ical.py", line 1, in <module>
        from __future__ import print_function
      File "ical.py", line 8, in main
        c = Calendar(infile.read())
      File "xxxxxxxx/venv/lib/python2.7/site-packages/ics/icalendar.py", line 60, in __init__
        container = string_to_container(imports)
      File "xxxxxxxx/venv/lib/python2.7/site-packages/ics/parse.py", line 166, in string_to_container
        return lines_to_container(txt.split('\n'))
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2179: ordinal not in range(128)
    Uncaught exception. Entering post mortem debugging
    Running 'cont' or 'step' will restart the program
    > xxxxxxxx/venv/lib/python2.7/site-packages/ics/parse.py(166)string_to_container()
    -> return lines_to_container(txt.split('\n'))
    (Pdb) pp txt[2123:2200]
    'CREATED:20120221T000100Z\r\nDESCRIPTION:Hello\\,\\n\\nSince I\xe2\x80\x99d like to show and'
    (Pdb)

Superficially, seems like a duplicate of issue #99 (based on the error message) but that one looks like it failed while emitting an event whereas this is failing during the read-in.

I didn't see anything in the ics.py docs about needing to specify an encoding, and the fact that `txt` appears to have the content suggests it's not a problem reading the bytes from the file; yet no-one else (aside from #99) seem to have reported this problem.  Is there something I'm missing?

Thanks,
-Neil

**Comment by neilr8133** [comment]
(For those who come after me.)  I'm still trying to wrap my head around it but it looks like the .ICS file is in UTF-8 format, which--for this conversation--is not handled 'properly' by the read-in code I was using:

    with open(input_file, 'r') as infile:
        c = Calendar(infile.read())

Per https://stackoverflow.com/a/844443 I tried changing to:

    import io
    infile = io.open(input_file, mode="r", encoding="utf-8")
    c = Calendar(infile.read())

and everything seemed to work fine.  So it looks like it's not an error in the code after all; however a note in the docs to be wary of this might help those who come after.

In my opinion, this issue can be closed (I'm leaving it open so that the devs can reference it in commits if they decide they *do* want to add a note in the docs).

**Comment by C4ptainCrunch** [comment]
We are in the process of removing support for Python2 so this kind of issue will be much less likely to appear but i'll try to drop a line in the doc :)
