### ISSUE TITLE
ics.parse.ParseError

### ISSUE THREAD

**Issue by xyzajacf** [C4ptainCrunch/ics.py#156]
Hey Guys, I am a python beginner. And trying to use your examples. So I have tryied to import local .ics exported from ical max osx.
```
from ics import Calendar
try:
    from urllib2 import urlopen          # py2
except ImportError:
    from urllib.request import urlopen   # py3
url = "file:/path/to/calendar.ics"
c = Calendar(urlopen(url).read().decode('iso-8859-1'))

import requests    # Alternative: use requests
c = Calendar(requests.get(url).text)

c
```
Which outputs to parsing error.

```
Traceback (most recent call last):
  File "Calendar Event Maker.py", line 10, in <module>
    c = Calendar(urlopen(url).read().decode('iso-8859-1'))
  File "/Library/Python/2.7/site-packages/ics/icalendar.py", line 69, in __init__
    self._populate(container[0])  # Use first calendar
  File "/Library/Python/2.7/site-packages/ics/component.py", line 60, in _populate
    extractor.function(self, lines)  # Send a list or empty list
  File "/Library/Python/2.7/site-packages/ics/icalendar.py", line 214, in events
    calendar.events = list(map(event_factory, lines))
  File "/Library/Python/2.7/site-packages/ics/icalendar.py", line 213, in event_factory
    return Event._from_container(x, tz=calendar._timezones)
  File "/Library/Python/2.7/site-packages/ics/component.py", line 32, in _from_container
    k._populate(container)
  File "/Library/Python/2.7/site-packages/ics/component.py", line 60, in _populate
    extractor.function(self, lines)  # Send a list or empty list
  File "/Library/Python/2.7/site-packages/ics/event.py", line 497, in alarms
    event.alarms = list(map(alarm_factory, lines))
  File "/Library/Python/2.7/site-packages/ics/event.py", line 496, in alarm_factory
    return af._from_container(x)
  File "/Library/Python/2.7/site-packages/ics/component.py", line 32, in _from_container
    k._populate(container)
  File "/Library/Python/2.7/site-packages/ics/component.py", line 63, in _populate
    extractor.function(self, lines[0])  # Send the element
  File "/Library/Python/2.7/site-packages/ics/alarm.py", line 201, in trigger
    alarm.trigger = parse_duration(line.value[1:])
  File "/Library/Python/2.7/site-packages/ics/utils.py", line 98, in parse_duration
    raise parse.ParseError()
ics.parse.ParseError
```

Do you have an idea what could be problem?

**Comment by C4ptainCrunch** [comment]
Could you post the file that gives you this error ?

**Comment by C4ptainCrunch** [comment]
I'm closing this as more a question than a bug and the thread is inactive. Feel free to repoen if you have something new to add :)

**Comment by ondrsalf** [comment]
I've to admit, I don't know if thats the same problem, but I encounter a similar error while trying to parse a ics-file I exported from my ownCloud.
I'm not a developer, but as far as I get the source code, this line should contain a minus after the 'DURATION:'

`
TRIGGER;VALUE=DURATION:PT0S
`

At the file 'alarm.py', the first letter gets cut off, afterwards the duration is passed to the parse_duration function, which searches for a 'P', which we just cut off....

[testics.ics.gz](https://github.com/C4ptainCrunch/ics.py/files/3545748/testics.ics.gz)
