### ISSUE TITLE
ValueError: A VEVENT must have at most one STATUS

### ISSUE THREAD

**Issue by aceisace** [C4ptainCrunch/ics.py#186]
@C4ptainCrunch 
Hi again. Thanks for the hard work and the new release :)

I've been testing the new release (v0.5) and came across the error from the description when trying to parse a yahoo icalendar (the same one I sent you before). Strangely, this error does not happen with google icalendar so I can't pinpoint the issue.

This is the full error report:
```
Traceback (most recent call last):
  File "<pyshell#14>", line 1, in <module>
    ical = Calendar(str(urlopen(yahoo_ical_url).read().decode()))
  File "/home/pi/.local/lib/python3.5/site-packages/ics/icalendar.py", line 68, in __init__
    self._populate(container[0])  # Use first calendar
  File "/home/pi/.local/lib/python3.5/site-packages/ics/component.py", line 59, in _populate
    extractor.function(self, lines)  # Send a list or empty list
  File "/home/pi/.local/lib/python3.5/site-packages/ics/icalendar.py", line 207, in events
    calendar.events = set(map(event_factory, lines))
  File "/home/pi/.local/lib/python3.5/site-packages/ics/icalendar.py", line 206, in event_factory
    return Event._from_container(x, tz=calendar._timezones)
  File "/home/pi/.local/lib/python3.5/site-packages/ics/component.py", line 31, in _from_container
    k._populate(container)
  File "/home/pi/.local/lib/python3.5/site-packages/ics/component.py", line 56, in _populate
    .format(container.name, extractor.type))
ValueError: A VEVENT must have at most one STATUS
```

Any ideas what I could do to get this working? Thanks in advance.

**Comment by C4ptainCrunch** [comment]
I took a look at your input file, you indeed have 2 time the line `STATUS:CONFIRMED` in the same event.

If you take a look at the RFC 5545, in section 3.6.1 it says:
```
; The following are OPTIONAL,
; but MUST NOT occur more than once.
;
class / created / description / geo /
last-mod / location / organizer / priority /
seq / status / summary / transp /
url / recurid /
```
The RFC says your file is invalid, so is ics.py, i'm sorry about that :/
Maybe we should add an option to only report rfc violations and not throw a value error but it won't be in 0.6
