### ISSUE TITLE
ContentLine parsing doesn't support quoted semicolons ('\;')

### ISSUE THREAD

**Issue by jhleath** [C4ptainCrunch/ics.py#193]
See https://tools.ietf.org/html/rfc5545#page-46

Minimal Example:

```
BEGIN:VCALENDAR
PRODID:-//Google Inc//Google Calendar 70.9054//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-WR-CALNAME:testcal
X-WR-TIMEZONE:America/New_York
BEGIN:VTIMEZONE
TZID:America/New_York
X-LIC-LOCATION:America/New_York
BEGIN:DAYLIGHT
TZOFFSETFROM:-0500
TZOFFSETTO:-0400
TZNAME:EDT
DTSTART:19700308T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0400
TZOFFSETTO:-0500
TZNAME:EST
DTSTART:19701101T020000
RRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
DTSTART:20190504T220000Z
DTEND:20190505T030000Z
DTSTAMP:20190812T114308Z
ORGANIZER;CN=Tester:mailto:tester@gmail.com
UID:na
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;CN=Te
 ester Participant;X-NUM-GUESTS=0:mailto:testpart@gmail.com
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;CN=tester
 parti@gmail.com;X-NUM-GUESTS=0;X-RESPONSE-COMMENT="RSVP-ing for nanana. I&
 rsquo\;ll be in NYC but he&rsquo\;ll be there :) ":mailto:testerpartic@gma
 il.com
CREATED:20190403T132708Z
DESCRIPTION:na
LAST-MODIFIED:20190504T213841Z
LOCATION:na
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:unneeded
TRANSP:OPAQUE
END:VEVENT
END:VCALENDAR
```

Redacted most of the identifying information. With the current code, I see:

```
Traceback (most recent call last):
  File "connections/ical.py", line 111, in <module>
    main()
  File "connections/ical.py", line 107, in main
    c = Calendar(f.read())
  File "/home/hleath/code/connections/ics/icalendar.py", line 64, in __init__
    container = string_to_container(imports)
  File "/home/hleath/code/connections/ics/parse.py", line 174, in string_to_container
    return lines_to_container(txt.splitlines())
  File "/home/hleath/code/connections/ics/parse.py", line 170, in lines_to_container
    return parse(tokenize_line(unfold_lines(lines)))
  File "/home/hleath/code/connections/ics/parse.py", line 163, in parse
    res.append(Container.parse(line.value, tokenized_lines))
  File "/home/hleath/code/connections/ics/parse.py", line 117, in parse
    items.append(Container.parse(line.value, tokenized_lines))
  File "/home/hleath/code/connections/ics/parse.py", line 115, in parse
    for line in tokenized_lines:
  File "/home/hleath/code/connections/ics/parse.py", line 156, in tokenize_line
    yield ContentLine.parse(line)
  File "/home/hleath/code/connections/ics/parse.py", line 79, in parse
    raise ParseError("No '=' in line '{}'".format(paramstr))
ics.parse.ParseError: No '=' in line 'll be in NYC but he&rsquo\'
```

By changing this line https://github.com/C4ptainCrunch/ics.py/blob/master/ics/parse.py#L69 to

```
splitted = re.split(r'[^\\];', key)
```

The file now parses correctly.

Additionally, the file passes validation at https://icalendar.org/validator.html .

**Comment by C4ptainCrunch** [comment]
Indeed, this is a bug :/

Here is an even more minimal example.
```
BEGIN:VCALENDAR
BEGIN:VEVENT
ATTENDEE;X-RESPONSE-COMMENT="I&rsquo\;ll be in NYC":mailto:example@example.com
END:VEVENT
END:VCALENDAR
```

**Comment by C4ptainCrunch** [comment]
@jhleath I tried your fix (in https://github.com/C4ptainCrunch/ics.py/commit/8779eb27205dc86536777c82fd7d5f2cdc3f29a2) but it does not work as the split also captures the char before the `;` and it is lost. (you can see the results in the travis tests)
I guess ics.py should use a real parser all the way to avoid things like that :/

**Comment by jhleath** [comment]
Ah - that's a good point - I was just trying to work around the exception and didn't notice the actual content coming out wrong.

**Comment by C4ptainCrunch** [comment]
I'm working on a [branch](https://github.com/C4ptainCrunch/ics.py/tree/tatsu) that uses a formal grammar (see [`grammar.ebnf`](https://github.com/C4ptainCrunch/ics.py/blob/tatsu/grammar.ebnf)) that solves both issues.

This is still an experiment, but working with a real parser looks like the way to go.
