### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by elouet** [C4ptainCrunch/ics.py#212]
I used ics successfully on a PC, now moving to a new machine, I get the following on a debian install : 
lou@oshima-vbox:~$ python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ics
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/ics/__init__.py", line 3, in <module>
    from .alarm import AudioAlarm, DisplayAlarm
  File "/usr/local/lib/python3.5/dist-packages/ics/alarm/__init__.py", line 1, in <module>
    from ics.alarm.audio import AudioAlarm
  File "/usr/local/lib/python3.5/dist-packages/ics/alarm/audio.py", line 31
    self._sound: Optional[ContentLine] = None
               ^
SyntaxError: invalid syntax

**Comment by elouet** [comment]
Upgrading to Python 3.7.5 fixed it..
