### ISSUE TITLE
Error when parsing times

### ISSUE THREAD

**Issue by buzypi** [C4ptainCrunch/ics.py#61]
I have an event with the following details from a Google Calendar ICS file:

```
BEGIN:VEVENT
DTSTART;VALUE=DATE:20110519
DTEND;VALUE=DATE:20110520
RRULE:FREQ=YEARLY
DTSTAMP:20150223T150857Z
UID:someuid
CREATED:20130514T081129Z
DESCRIPTION:
LAST-MODIFIED:20130514T081155Z
LOCATION:
SEQUENCE:1
STATUS:CONFIRMED
SUMMARY:Event Details
TRANSP:TRANSPARENT
END:VEVENT
```

and when trying to parse this, I am getting the following error:

`ParserError: Could not match input to any of ['YYYY-MM-DDTHH:mm'] on '20150223T150857Z'`

**Comment by jammon** [comment]
I got the same error message when I tried to replicate the first example from the docs:

```
>>> from ics import Calendar
>>> from urllib2 import urlopen
>>> url = "http://hackeragenda.urlab.be/events/events.ics"
>>> c = Calendar(urlopen(url).read().decode('iso-8859-1'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../venvs/test/lib/python2.7/site-packages/ics/icalendar.py", line 71, in __init__
    self._populate(container[0])  # Use first calendar
  File "/.../venvs/test/lib/python2.7/site-packages/ics/component.py", line 52, in _populate
    extractor.function(self, lines)  # Send a list or empty list
  File "/.../venvs/test/lib/python2.7/site-packages/ics/icalendar.py", line 233, in events
    calendar.events = list(map(event_factory, lines))
  File "/.../venvs/test/lib/python2.7/site-packages/ics/icalendar.py", line 232, in <lambda>
    event_factory = lambda x: Event._from_container(x, tz=calendar._timezones)
  File "/.../venvs/test/lib/python2.7/site-packages/ics/component.py", line 31, in _from_container
    k._populate(container)
  File "/.../venvs/test/lib/python2.7/site-packages/ics/component.py", line 55, in _populate
    extractor.function(self, lines[0])  # Send the element
  File "/.../venvs/test/lib/python2.7/site-packages/ics/event.py", line 293, in created
    event.created = iso_to_arrow(line, tz_dict)
  File "/.../venvs/test/lib/python2.7/site-packages/ics/utils.py", line 50, in iso_to_arrow
    return arrow.get(val)
  File "/.../venvs/test/lib/python2.7/site-packages/arrow/api.py", line 23, in get
    return _factory.get(*args, **kwargs)
  File "/.../venvs/test/lib/python2.7/site-packages/arrow/factory.py", line 163, in get
    dt = parser.DateTimeParser(locale).parse_iso(arg)
  File "/.../venvs/test/lib/python2.7/site-packages/arrow/parser.py", line 100, in parse_iso
    return self._parse_multiformat(string, formats)
  File "/.../venvs/test/lib/python2.7/site-packages/arrow/parser.py", line 243, in _parse_multiformat
    raise ParserError('Could not match input to any of {0} on \'{1}\''.format(formats, string))
arrow.parser.ParserError: Could not match input to any of ['YYYY-MM-DDTHH:mm'] on '20140513T190000Z'
```

**Comment by jammon** [comment]
This diff
```
--- a/ics/utils.py
+++ b/ics/utils.py
@@ -47,7 +47,7 @@ def iso_to_arrow(time_container, available_tz={}):
         selected_tz = available_tz.get(tz, 'UTC')
         return arrow.get(naive, selected_tz)
     else:
-        return arrow.get(val)
+        return arrow.get(val, ['YYYYMMDDTHHmm', 'YYYYMMDDTHHmmss'])
```
seems to fix it. But how can this have worked in the first place?

**Comment by C4ptainCrunch** [comment]
Tanks for reporting this issue :)
Arrow (a dependency) changed it's API in a backwards-incompatible way and it's seems to break everything. 

The last version of ics.py (0.3) was done mostly to pin arrow to `arrow==0.4.2` (the last compatible version). It seemed fixed but it's not the case anymore :/

A hotfix would be for you to install ics first an then run `pip install arrow==0.4.2` to downgrade arrow.

The next version of ics.py should be arrow-free (this lib caused too much trouble) :)
